import type { User } from "../types"

export const USERS: User[] = [
  {
    id: "u1",
    firstName: "Arta",
    lastName: "Kryeziu",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    isOnline: true,
  },
  {
    id: "u2",
    firstName: "Elira",
    lastName: "Meta",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    isOnline: false,
  },
  {
    id: "u3",
    firstName: "Gentiana",
    lastName: "Hasani",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    isOnline: true,
  },
  {
    id: "u4",
    firstName: "Flora",
    lastName: "Berisha",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    isOnline: false,
  },
  {
    id: "u5",
    firstName: "Alba",
    lastName: "Dervishi",
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
    isOnline: true,
  },
  {
    id: "u6",
    firstName: "Nora",
    lastName: "Gashi",
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    isOnline: false,
  },
  {
    id: "u7",
    firstName: "Rea",
    lastName: "Tafa",
    avatar: "https://randomuser.me/api/portraits/women/27.jpg",
    isOnline: true,
  },
  {
    id: "u8",
    firstName: "Blerta",
    lastName: "Zeqiri",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    isOnline: false,
  },
  {
    id: "u9",
    firstName: "Vesa",
    lastName: "Nikolla",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    isOnline: true,
  },
  {
    id: "u10",
    firstName: "Jonida",
    lastName: "Lluka",
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    isOnline: false,
  },
  {
    id: "u11",
    firstName: "Drilona",
    lastName: "Basha",
    avatar: "https://randomuser.me/api/portraits/women/31.jpg",
    isOnline: true,
  },
  {
    id: "u12",
    firstName: "Erisa",
    lastName: "Deda",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    isOnline: false,
  },
  {
    id: "u13",
    firstName: "Arlinda",
    lastName: "Cana",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    isOnline: true,
  },
  {
    id: "u14",
    firstName: "Linda",
    lastName: "Shala",
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    isOnline: false,
  },
  {
    id: "u15",
    firstName: "Anila",
    lastName: "Beqiri",
    avatar: "https://randomuser.me/api/portraits/women/35.jpg",
    isOnline: true,
  },
  {
    id: "u16",
    firstName: "Enxhi",
    lastName: "Mira",
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    isOnline: false,
  },
  {
    id: "u17",
    firstName: "Mira",
    lastName: "Rama",
    avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    isOnline: true,
  },
  {
    id: "u18",
    firstName: "Lira",
    lastName: "Hoti",
    avatar: "https://randomuser.me/api/portraits/women/38.jpg",
    isOnline: false,
  },
  {
    id: "u19",
    firstName: "Klea",
    lastName: "Lusha",
    avatar: "https://randomuser.me/api/portraits/women/39.jpg",
    isOnline: true,
  },
  {
    id: "u20",
    firstName: "Ilira",
    lastName: "Peci",
    avatar: "https://randomuser.me/api/portraits/women/40.jpg",
    isOnline: false,
  },
]
